[project]
name = "minimum-enclosing-circle"
version = "0.1.0"
description = "Výpočet minimálního kruhu obalujícího body"
authors = [{name = "Tvoje jméno"}]
dependencies = ["numpy", "matplotlib"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"